language: node_js
sudo: required
dist: trusty

node_js:
  - "6"
  - "8.2.1"
# later node versions should be reenabled. See https://github.com/glimmerjs/glimmer-resolver/issues/22
# was fixed to 8.2.1 to solve See https://github.com/glimmerjs/glimmer-resolver/issues/19
# to reenable, uncomment the next line:
# - "node"

addons:
  firefox: "latest"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
